<?php
$registration_inner="
<option value='OPTIONAL'>OPTIONAL</option>
<option value='COMPULSORY'>COMPULSORY</option>
";

$authentication_inner="
<option value='LDAP'>LDAP</potion>	
<option value='MOODLE'>MOODLE</potion>	
<option value='NATIVE'>NATIVE</potion>	
";
/*Auto generated by form_gen.php*/
$fields=array(
	
"program_id"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.NumberTextBox",
		"type"=>"hidden",
		"required"=>"false",
		"label"=>"Program id",
		"value"=>""),	
"short_name"=>array(
		"length"=>"140",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Short name",
		"value"=>""),	
"description"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Description",
		"maxLength"=>"200",
		"value"=>""),	
"registration"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.ComboBox",
		"inner"=>$registration_inner,
		"required"=>"true",
		"label"=>"Registration",
		"value"=>""),	
"authentication"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.ComboBox",
		"inner"=>$authentication_inner,
		"required"=>"true",
		"label"=>"Authentication",
		"value"=>""),	
"code"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Code",
		"value"=>""),	
"coordinator"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Coordinator",
		"value"=>""),	
"disabled"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.NumberTextBox",
		"required"=>"false",
		"label"=>"Disabled",
		"value"=>""),	
"starting_at"=>array(
		"length"=>"100",
		"dojoType"=>"dijit.form.DateTextBox",
		"required"=>"false",
		"label"=>"Starting From",
		"value"=>""),	
"ending_at"=>array(
		"length"=>"100",
		"dojoType"=>"dijit.form.DateTextBox",
		"required"=>"false",
		"label"=>"Ending On",
		"value"=>""),	
/*
"deleted"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.NumberTextBox",
		"required"=>"false",
		"label"=>"Deleted",
		"value"=>""),	
 */
"note"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.SimpleTextarea",
		"required"=>"false",
		"label"=>"Note",
		"value"=>"")	
);
?>
