<!--Auto generated by form_gen.php-->
<?php
$help_array=array(
'middle_names'=>'Enter your Middle name(s) if available',
'corresp_addr'=>'Please select PERMANENT or OFFICE as your correspondent address',
'degree_title_2'=>'Title of your first degree 2 (eg:)',
'email'=>'This E-mail address will use as your username  to login to the system',
'address1'=>'Your street address eg: 24/1, First cross street'
);
 ?>
