<!--Auto generated by form_gen.php-->
<?php
$help_array=array(
'id'=>'Id',
'proto'=>'Proto',
'timestamp'=>'Timestamp',
'user_id'=>'User id',
'ip'=>'Ip',
'page'=>'Page',
'module'=>'Module',
'cmid'=>'Cmid',
'action'=>'Action',
'url'=>'Url',
'deleted'=>'Deleted',
'note'=>'Note',
'info'=>'Info',
'host'=>'Host',
'request'=>'Request',
'agent'=>'Agent');
 ?>
