<!--Auto generated by form_gen.php-->
<?php
$help_array=array(
'user_id'=>'User id',
'syear'=>'Syear',
'current_school_id'=>'Current school id',
'title'=>'Title',
'first_name'=>'First name',
'last_name'=>'Last name',
'middle_name'=>'Middle name',
'username'=>'Username',
'password'=>'Password',
'phone'=>'Phone',
'email'=>'Email',
'permission'=>'Permission',
'theme'=>'Theme',
'layout'=>'Layout',
'homeroom'=>'Homeroom',
'programs'=>'Programs',
'last_login'=>'Last login',
'failed_login'=>'Failed login',
'profile_id'=>'Profile id',
'rollover_id'=>'Rollover id',
'deleted'=>'Deleted',
'note'=>'Note');
 ?>
