<?php
/*Auto generated by form_gen.php*/
d_r("dojox.form.PasswordValidator");
$password_custom='
<input type="hidden" name="password" id="password" jsId="password" dojoType="dijit.form.ValidationTextBox" style="border:0px;width:0px;" value="" ></input>
<div dojoType="dijit.form.DropDownButton">
   <span>
       Change Password 
   </span>
   <div dojoType="dijit.TooltipDialog">
      <div dojoType="dojox.form.PasswordValidator" name="password_val" id="password_val" jsId="password_val">
         <table>
            <tr><td>Password</td><td>:<input type="password" pwType="new" ></td></tr>
            <tr><td>Validate</td><td>:<input type="password" pwType="verify" ></td></tr>
         </table>
      </div>
      <button dojoType="dijit.form.Button" type="submit">
         OK
           <script type="dojo/method" event="onClick" args="evt">
            var pval=dijit.byId("password_val").value;
            var pset=dijit.byId("password");
            pset.attr("value",pval);
            //alert(pset.value);
         </script>
      </button>
   </div>
</div>
';

$res=exec_query("SELECT group_name,rid FROM ".$GLOBALS['S_TABLES']['groups'],Q_RET_ARRAY,null,'group_name');
$group_inner      =gen_select_inner(array_keys($res));

$res=exec_query("SELECT short_name,rid FROM ".$GLOBALS['S_TABLES']['program'],Q_RET_ARRAY,null,'rid');
$program_inner  =gen_select_inner($res,'short_name');

$permission_inner =gen_select_inner(array("ADMIN","STAFF","STUDENT","GUEST"));
$theme_inner      =gen_select_inner(array('claro','nihilo','soria','tundra'));
$layout_inner     =gen_select_inner(array('web','app','pub'));
$title_list       =get_common_list('title');
$title_inner      =gen_select_inner($title_list['list'],null,true);

$syear_inner="";
$curr_year=date("Y");
for($i=($curr_year-2); $i < ($curr_year+2); $i++ ){
   $syear_inner.="<option value='$i'>$i</option>";
}


$fields=array(
   
"user_id"=>array(
      "length"=>"77",
      "dojoType"=>"dijit.form.NumberTextBox",
      "type"=>"hidden",
      "required"=>"false",
      "label"=>"User id",
      "value"=>""),   
"syear"=>array(
      "length"=>"70",
      "dojoType"=>"dijit.form.ComboBox",
      "required"=>"false",
      "inner"=>$syear_inner,
      "label"=>"Syear",
      "value"=>""),   
/*
"current_school_id"=>array(
      "length"=>"70",
      "dojoType"=>"dijit.form.ComboBox",
      "required"=>"false",
      "inner"=>$school_id_inner,
      "label"=>"Current school id",
      "value"=>""),   
 */
"title"=>array(
      "length"=>"35",
      "dojoType"=>"dijit.form.ComboBox",
      "required"=>"false",
      "label"=>"Title",
      "inner"=>$title_inner,
      "value"=>""),   
"first_name"=>array(
      "length"=>"350",
      "dojoType"=>"dijit.form.ValidationTextBox",
      "required"=>"false",
      "label"=>"First name",
      "value"=>""),   
"last_name"=>array(
      "length"=>"350",
      "dojoType"=>"dijit.form.ValidationTextBox",
      "required"=>"false",
      "label"=>"Last name",
      "value"=>""),   
"middle_names"=>array(
      "length"=>"350",
      "dojoType"=>"dijit.form.ValidationTextBox",
      "required"=>"false",
      "label"=>"Middle names",
      "value"=>""),   
"username"=>array(
      "length"=>"350",
      "dojoType"=>"dijit.form.ValidationTextBox",
      "required"=>"false",
      "label"=>"Username",
      "value"=>""),   
"password"=>array(
      "label"=>"Password",
      "custom"=>"true",
      "inner"=>$password_custom),   
/*
"password"=>array(
      "length"=>"350",
      "dojoType"=>"dijit.form.ValidationTextBox",
      "required"=>"false",
      "label"=>"Password",
      "value"=>""),   
*/
"phone"=>array(

      "length"=>"350",
      "dojoType"=>"dijit.form.ValidationTextBox",
      "required"=>"false",
      "label"=>"Phone",
      "value"=>""),   
"email"=>array(
      "length"=>"350",
      "dojoType"=>"dijit.form.ValidationTextBox",
      "required"=>"false",
      "label"=>"Email",
      "value"=>""),   
"ldap_user_id"=>array(
      "length"=>"350",
      "dojoType"=>"dijit.form.ValidationTextBox",
      "required"=>"false",
      "label"=>"LDAP User ID",
      "value"=>""),   

      /*
"permission"=>array(
      "length"=>"350",
      "dojoType"=>"dijit.form.SimpleTextarea",
      "required"=>"false",
      "inner"=>$permission_inner,
      "label"=>"Permission",
      "value"=>""),   
      */
"group_id"=>array(
      "length"=>"150",
      "dojoType"=>"dijit.form.Select",
      "required"=>"false",
      "inner"=>$group_inner,
      "label"=>"Group",
      "value"=>""),   
"theme"=>array(
      "length"=>"140",
      "dojoType"=>"dijit.form.Select",
      "required"=>"false",
      "label"=>"Theme",
      "inner"=>$theme_inner,
      "value"=>""),   
"layout"=>array(
      "length"=>"140",
      "dojoType"=>"dijit.form.Select",
      "required"=>"false",
      "inner"=>$layout_inner,
      "label"=>"Layout",
      "value"=>""),   
"homeroom"=>array(
      "length"=>"35",
      "dojoType"=>"dijit.form.ValidationTextBox",
      "required"=>"false",
      "label"=>"Homeroom",
      "value"=>""),   
"programs"=>array(
      "length"=>"150",
      "dojoType"=>"dijit.form.Select",
      "required"=>"false",
      "inner"=>$program_inner,
      "label"=>"Programs",
      "value"=>""),   
      /*
"last_login"=>array(
      "length"=>"100",
      "dojoType"=>"dijit.form.ValidationTextBox",
      "required"=>"true",
      "label"=>"Last login",
      "value"=>""),   
"failed_login"=>array(
      "length"=>"70",
      "dojoType"=>"dijit.form.ValidationTextBox",
      "required"=>"false",
      "label"=>"Failed login",
      "value"=>""),   
      */
"profile_id"=>array(
      "length"=>"70",
      "dojoType"=>"dijit.form.ValidationTextBox",
      "required"=>"false",
      "label"=>"Profile id",
      "value"=>""),   
"rollover_id"=>array(
      "length"=>"70",
      "dojoType"=>"dijit.form.ValidationTextBox",
      "required"=>"false",
      "label"=>"Rollover id",
      "value"=>""),   
      /*
"deleted"=>array(
      "length"=>"70",
      "dojoType"=>"dijit.form.NumberTextBox",
      "required"=>"false",
      "label"=>"Deleted",
      "value"=>""),   
      */
"note"=>array(
      "length"=>"350",
      "dojoType"=>"dijit.form.SimpleTextarea",
      "required"=>"false",
      "label"=>"Note",
      "value"=>"")   
);
?>
