<?php
/*Auto generated by form_gen.php*/
$fields=array(
   
"index_no"=>array(
      "length"=>"350",
      "dojoType"=>"dijit.form.ValidationTextBox",
      "required"=>"true",
      "label"=>"Index no",
      "value"=>""),   
"paper_id"=>array(
      "length"=>"77",
      "dojoType"=>"dijit.form.NumberTextBox",
      "required"=>"true",
      "label"=>"Paper id",
      "value"=>""),   
"answers"=>array(
      "length"=>"350",
      "dojoType"=>"dijit.form.SimpleTextarea",
      "required"=>"false",
      "label"=>"Answers",
      "value"=>""),   
"marks"=>array(
      "length"=>"77",
      "dojoType"=>"dijit.form.NumberTextBox",
      "required"=>"false",
      "label"=>"Marks",
      "value"=>""),   
"state"=>array(
      "length"=>"350",
      "dojoType"=>"dijit.form.ValidationTextBox",
      "required"=>"true",
      "label"=>"State",
      "value"=>""),   
"note"=>array(
      "length"=>"100",
      "dojoType"=>"dijit.form.SimpleTextarea",
      "required"=>"false",
      "label"=>"Note",
      "value"=>"")   
);
?>
