<?php
/*Auto generated by form_gen.php*/
$fields=array(
   
"course_id"=>array(
      "length"=>"350",
      "dojoType"=>"dijit.form.ValidationTextBox",
      "required"=>"true",
      "label"=>"Course id",
      "value"=>""),   
"course"=>array(
      "length"=>"350",
      "dojoType"=>"dijit.form.SimpleTextarea",
      "required"=>"false",
      "label"=>"Course",
      "value"=>""),   
"note"=>array(
      "length"=>"100",
      "dojoType"=>"dijit.form.SimpleTextarea",
      "required"=>"false",
      "label"=>"Note",
      "value"=>"")   
);
?>
