<!--Auto generated by form_gen.php-->
<div dojoType='dijit.Tooltip' connectId='course_id' >
	<b>HELP:</b>
	<div style='max-width:400px;border-top:1px solid silver;text-align:justify'>
		Course id
	</div>
</div>
<div dojoType='dijit.Tooltip' connectId='course' >
	<b>HELP:</b>
	<div style='max-width:400px;border-top:1px solid silver;text-align:justify'>
		Course
	</div>
</div>
<div dojoType='dijit.Tooltip' connectId='note' >
	<b>HELP:</b>
	<div style='max-width:400px;border-top:1px solid silver;text-align:justify'>
		Note
	</div>
</div>
