<?php
/*Auto generated by form_gen.php*/
$fields=array(
   
"exam_id"=>array(
      "length"=>"350",
      "dojoType"=>"dijit.form.ValidationTextBox",
      "required"=>"true",
      "label"=>"Exam id",
      "value"=>""),   
"exam"=>array(
      "length"=>"350",
      "dojoType"=>"dijit.form.SimpleTextarea",
      "required"=>"true",
      "label"=>"Exam",
      "value"=>""),   
"exam_date"=>array(
      "length"=>"100",
      "dojoType"=>"dijit.form.DateTextBox",
      "required"=>"true",
      "label"=>"Exam date",
      "value"=>""),   
"note"=>array(
      "length"=>"100",
      "dojoType"=>"dijit.form.SimpleTextarea",
      "required"=>"false",
      "label"=>"Note",
      "value"=>"")   
);
?>
