<!--Auto generated by form_gen.php-->
<div dojoType='dijit.Tooltip' connectId='question' >
	<b>HELP:</b>
	<div style='max-width:400px;border-top:1px solid silver;text-align:justify'>
		Question
	</div>
</div>
<div dojoType='dijit.Tooltip' connectId='paper_id' >
	<b>HELP:</b>
	<div style='max-width:400px;border-top:1px solid silver;text-align:justify'>
		Paper id
	</div>
</div>
<div dojoType='dijit.Tooltip' connectId='A' >
	<b>HELP:</b>
	<div style='max-width:400px;border-top:1px solid silver;text-align:justify'>
		A
	</div>
</div>
<div dojoType='dijit.Tooltip' connectId='B' >
	<b>HELP:</b>
	<div style='max-width:400px;border-top:1px solid silver;text-align:justify'>
		B
	</div>
</div>
<div dojoType='dijit.Tooltip' connectId='C' >
	<b>HELP:</b>
	<div style='max-width:400px;border-top:1px solid silver;text-align:justify'>
		C
	</div>
</div>
<div dojoType='dijit.Tooltip' connectId='D' >
	<b>HELP:</b>
	<div style='max-width:400px;border-top:1px solid silver;text-align:justify'>
		D
	</div>
</div>
<div dojoType='dijit.Tooltip' connectId='E' >
	<b>HELP:</b>
	<div style='max-width:400px;border-top:1px solid silver;text-align:justify'>
		E
	</div>
</div>
<div dojoType='dijit.Tooltip' connectId='BLANK' >
	<b>HELP:</b>
	<div style='max-width:400px;border-top:1px solid silver;text-align:justify'>
		Blank
	</div>
</div>
<div dojoType='dijit.Tooltip' connectId='NOA' >
	<b>HELP:</b>
	<div style='max-width:400px;border-top:1px solid silver;text-align:justify'>
		Noa
	</div>
</div>
<div dojoType='dijit.Tooltip' connectId='note' >
	<b>HELP:</b>
	<div style='max-width:400px;border-top:1px solid silver;text-align:justify'>
		Note
	</div>
</div>
