<!--Auto generated by form_gen.php-->
<style type="text/css">.helptt{max-width:400px;border-top:1px solid silver;text-align:justify;}</style>
<div dojoType='dijit.Tooltip' connectId='paper_id' >
   <b>HELP:</b>
   <div class='helptt'>
      Paper id
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='course_id' >
   <b>HELP:</b>
   <div class='helptt'>
      Course id
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='exam_id' >
   <b>HELP:</b>
   <div class='helptt'>
      Exam id
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='examiner' >
   <b>HELP:</b>
   <div class='helptt'>
      Examiner
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='no_of_questions' >
   <b>HELP:</b>
   <div class='helptt'>
      No of questions
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='sections' >
   <b>HELP:</b>
   <div class='helptt'>
      Comma seperated number of questions for each section eg: 20,20,20 - three sections where firts section with 20 questions second with 20 and third with 20. total number of questions is 60.
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='answer_file' >
   <b>HELP:</b>
   <div class='helptt'>
      Answer file
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='mark_logic_file' >
   <b>HELP:</b>
   <div class='helptt'>
      Mark logic file
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='state' >
   <b>HELP:</b>
   <div class='helptt'>
      State
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='index_delimiter' >
   <b>HELP:</b>
   <div class='helptt'>
      Index number and the answer string will delimited by this sign   eg: ';:;' -
      <pre>
Index;:;Answer1;Answer2;Answer3;Answer4;Answer5;Answer6;...
1330004;:;C;D;D;C;C;BLANK;...
1330005;:;C;D;D;B;D;E;B;D;...
      </pre>
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='question_delimiter' >
   <b>HELP:</b>
   <div class='helptt'>
      Answers for each question will be delimited by this sign eg:';'  -
      <pre>
Index;:;Answer1;Answer2;Answer3;Answer4;Answer5;Answer6;...
1330004;:;C;D;D;C;C;BLANK;...
1330005;:;C;D;D;B;D;E;B;D;...
      </pre>
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='answer_delimiter' >
   <b>HELP:</b>
   <div class='helptt'>
      Multiple answers will delimited by this sign eg:'[(,)]' -
      <pre>
Index;:;Answer1;Answer2;Answer3;Answer4;Answer5;Answer6;...
1223084;:;B;(C,D);(C,D,E);E;D;...
      </pre>
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='first_line_header' >
   <b>HELP:</b>
   <div class='helptt'>
      Select TRUE if the first line of the answer csv is the header of the file ( not a data line )
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='blank_answer' >
   <b>HELP:</b>
   <div class='helptt'>
      How is the blank answers denoted eg: 'BLANK'
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='no_answer' >
   <b>HELP:</b>
   <div class='helptt'>
      How is the no answer questions were denoted eg: 'NOA'
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='logic_question_delimiter' >
   <b>HELP:</b>
   <div class='helptt'>
      Question number and the answer string will delimited by this sign   eg: ';:;' -
      <pre>
Q;:;A;B;C;D;E;NOA;BLANK
15;:;-25;-25;-25;100;-25;0;0
16;:;-25;100;-25;-25;-25;0;0
      </pre>
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='logic_option_delimiter' >
   <b>HELP:</b>
   <div class='helptt'>
      Options for the given logic will be delimited by this sign eg: ';' -
      <pre>
Q;:;A;B;C;D;E;NOA;BLANK
15;:;-25;-25;-25;100;-25;0;0
16;:;-25;100;-25;-25;-25;0;0
      <pre>
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='logic_first_line_header' >
   <b>HELP:</b>
   <div class='helptt'>
      Select TRUE if the first line of the marking logic csv is the header of the file ( not a data line )
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='note' >
   <b>HELP:</b>
   <div class='helptt'>
      Note
   </div>
</div>
