<?php
/*Auto generated by form_gen.php*/

$course_id_inner	="";
$exam_id_inner		="";

$res=exec_query("SELECT course_id FROM ".$GLOBALS['MOD_P_TABLES']['course'],Q_RET_MYSQL_RES);
while($row=mysql_fetch_assoc($res)){
	$course_id_inner	.="<option value='".$row['course_id']."'>".$row['course_id']."</option>";
}

$res=exec_query("SELECT exam_id FROM ".$GLOBALS['MOD_P_TABLES']['exam'],Q_RET_MYSQL_RES);
while($row=mysql_fetch_assoc($res)){
	$exam_id_inner	.="<option value='".$row['exam_id']."'>".$row['exam_id']."</option>";
}

$yes_no_inner="";
foreach(array('0','1') as $value){
	$yes_no_inner.="<option value='$value'>$value</option>";
}

include_once(MOD_CLASSES."/file_uploader_class.php");
$file_uploader		= new File_uploader(MOD_A_CSV,'test.csv');
$mark_logic_file_inner=$file_uploader->client_side_handle("frm1","mark_logic_file1","Upload",null,'paper_id');

$file_uploader		= new File_uploader(MOD_A_CSV,'test.csv');
$answer_file_inner=$file_uploader->client_side_handle("frm2","answer_file1","Upload",null,'paper_id');

$fields=array(
	
"paper_id"=>array(
		"length"=>"77",
		"dojoType"=>"dijit.form.NumberTextBox",
		"type"=>"hidden",
		"required"=>"false",
		"label"=>"",
		"style"=>"border:0px;",
		"value"=>""),	
"course_id"=>array(
		"length"=>"150",
		"dojoType"=>"dijit.form.ComboBox",
		"required"=>"true",
		"label"=>"Course id",
		"inner"=>$course_id_inner,
		"value"=>""),	
"exam_id"=>array(
		"length"=>"150",
		"dojoType"=>"dijit.form.ComboBox",
		"required"=>"true",
		"inner"=>$exam_id_inner,
		"label"=>"Exam id",
		"value"=>""),	
	
"examiner"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.SimpleTextarea",
		"required"=>"false",
		"label"=>"Examiner",
		"value"=>""),	
"no_of_questions"=>array(
		"length"=>"77",
		"dojoType"=>"dijit.form.NumberTextBox",
		"required"=>"true",
		"label"=>"No of questions",
		"value"=>""),	
"sections"=>array(
		"length"=>"140",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Sections",
		"value"=>""),	
"answer_file_uploader"=>array(
		"label"=>"Answer file uploader",
		"custom"=>"true",
		"inner"=>$answer_file_inner
		),	
"answer_file"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"disabled"=>"true",
		"label"=>"Answer file",
		"value"=>""),	
"mark_logic_file_uploader"=>array(
		"custom"=>"true",
		"inner"=>$mark_logic_file_inner,
		"label"=>"Mark logic file Uploader"
		),	
"mark_logic_file"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"disabled"=>"true",
		"label"=>"Mark logic file",
		"value"=>""),	

"state"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"State",
		"value"=>""),	
"index_delimiter"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"label"=>"Index delimiter",
		"value"=>";:;"),	
"question_delimiter"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"label"=>"Question delimiter",
		"value"=>";"),	
"answer_delimiter"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"label"=>"Answer delimiter",
		"value"=>"[(,)]"),	
"first_line_header"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.ComboBox",
		"required"=>"false",
		"label"=>"First line header",
		"inner"=>$yes_no_inner,
		"value"=>"1"),	
"blank_answer"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"label"=>"Blank answer",
		"value"=>"BLANK"),	
"no_answer"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"label"=>"No answer",
		"value"=>"NOA"),	
"logic_question_delimiter"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"label"=>"Logic question delimiter",
		"value"=>";:;"),	
"logic_option_delimiter"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"label"=>"Logic option delimiter",
		"value"=>";"),	
"logic_first_line_header"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.ComboBox",
		"required"=>"false",
		"inner"=>$yes_no_inner,
		"label"=>"Logic first line header",
		"value"=>"1"),	
"note"=>array(
		"length"=>"100",
		"dojoType"=>"dijit.form.SimpleTextarea",
		"required"=>"false",
		"label"=>"Note",
		"value"=>"")	
);
?>
