<!--Auto generated by form_gen.php-->
<div dojoType='dijit.Tooltip' connectId='id' >
   <b>HELP:</b>
   <div style='max-width:400px;border-top:1px solid silver;text-align:justify'>
      Id
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='short_name' >
   <b>HELP:</b>
   <div style='max-width:400px;border-top:1px solid silver;text-align:justify'>
      Short name
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='exam_date' >
   <b>HELP:</b>
   <div style='max-width:400px;border-top:1px solid silver;text-align:justify'>
      Exam date
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='sheet_header' >
   <b>HELP:</b>
   <div style='max-width:400px;border-top:1px solid silver;text-align:justify'>
      Sheet header
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='full_name' >
   <b>HELP:</b>
   <div style='max-width:400px;border-top:1px solid silver;text-align:justify'>
      Full name
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='logo' >
   <b>HELP:</b>
   <div style='max-width:400px;border-top:1px solid silver;text-align:justify'>
      Logo
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='table_prefix' >
   <b>HELP:</b>
   <div style='max-width:400px;border-top:1px solid silver;text-align:justify'>
      Table prefix
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='deleted' >
   <b>HELP:</b>
   <div style='max-width:400px;border-top:1px solid silver;text-align:justify'>
      Deleted
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='note' >
   <b>HELP:</b>
   <div style='max-width:400px;border-top:1px solid silver;text-align:justify'>
      Note
   </div>
</div>
