<!--Auto generated by form_gen.php-->
<?php
$help_array=array(
'eligibility_name'=>'Eligibility name',
'eligibility_year'=>'Eligibility year',
'GPA1'=>'Gpa1',
'GPA2'=>'Gpa2',
'GPA3'=>'Gpa3',
'GPA4'=>'Gpa4',
'GPA'=>'Gpa',
'credits1'=>'Credits1',
'credits2'=>'Credits2',
'credits3'=>'Credits3',
'credits4'=>'Credits4',
'credits'=>'Credits',
'courses_year1'=>'Courses year1',
'courses_year2'=>'Courses year2',
'courses_year3'=>'Courses year3',
'courses_year4'=>'Courses year4',
'attendance'=>'Attendance',
'pre_eligibility'=>'Pre eligibility',
'deleted'=>'Deleted',
'note'=>'Note');
 ?>
