<!--Auto generated by form_gen.php-->
<?php
$help_array=array(
'id'=>'Id',
'short_name'=>'Short name',
'full_name'=>'Full name',
'logo'=>'Logo',
'degree'=>'Degree',
'class'=>'Class',
'grade'=>'Grade',
'gpv'=>'Gpv',
'table_prefix'=>'Table prefix',
'deleted'=>'Deleted',
'note'=>'Note');
 ?>