<?php
/*Auto generated by form_gen.php*/
$fields=array(
   
"short_name"=>array(
      "length"=>"140",
      "dojoType"=>"dijit.form.ValidationTextBox",
      "required"=>"true",
      "label"=>"Short name",
      "value"=>""),   
"full_name"=>array(
      "length"=>"350",
      "dojoType"=>"dijit.form.ValidationTextBox",
      "required"=>"true",
      "label"=>"Full name",
      "value"=>""),   
"degree"=>array(
      "length"=>"350",
      "dojoType"=>"dijit.form.ValidationTextBox",
      "required"=>"true",
      "label"=>"Degree",
      "value"=>""),   
"class"=>array(
      "length"=>"350",
      "dojoType"=>"dijit.form.ValidationTextBox",
      "required"=>"true",
      "label"=>"Class",
      "value"=>""),   
"grade"=>array(
      "length"=>"350",
      "dojoType"=>"dijit.form.ValidationTextBox",
      "required"=>"true",
      "label"=>"Grade",
      "value"=>""),   
"gpv"=>array(
      "length"=>"350",
      "dojoType"=>"dijit.form.ValidationTextBox",
      "required"=>"true",
      "label"=>"Gpv",
      "value"=>""),   
"table_prefix"=>array(
      "length"=>"350",
      "dojoType"=>"dijit.form.ValidationTextBox",
      "required"=>"true",
      "label"=>"Table prefix",
      "value"=>"")   
);
?>
