<!--Auto generated by form_gen.php-->
<?php
$help_array=array(
	/*
'rec_id'=>'Rec id',
'registration_no'=>'Registration no',
'index_no'=>'Index no',
'registration_type'=>'Registration type',
'title'=>'Title',
'first_name'=>'First name',
	 */
'middle_names'=>'Enter your Middle name(s) if available',
/*
'last_name'=>'Last name',
 */
'NIC'=>'Without spaces<br/>NIC will also use as your password to login to the system',
/*
'DOB'=>'Dob',
'gender'=>'Gender',
'confirm'=>'Confirm',
 */
'degree_title_1'=>'Title of your first degree 1 (eg:)',
/*
'year_of_award_1'=>'Year of award 1',
'class_1'=>'Class 1',
'university_1'=>'University 1',
'date_entered_1'=>'Date entered 1',
'date_left_1'=>'Date left 1',
'subject1_1'=>'Subject1 1',
'subject2_1'=>'Subject2 1',
'subject3_1'=>'Subject3 1',
'subject4_1'=>'Subject4 1',
*/
'corresp_addr'=>'Please select PERMANENT or OFFICE as your correspondent address',
/*
*/
'degree_title_2'=>'Title of your first degree 2 (eg:)',
/*
'year_of_award_2'=>'Year of award 2',
'class_2'=>'Class 2',
'university_2'=>'University 2',
'date_entered_2'=>'Date entered 2',
'date_left_2'=>'Date left 2',
'subject1_2'=>'Subject1 2',
'subject2_2'=>'Subject2 2',
'subject3_2'=>'Subject3 2',
'subject4_2'=>'Subject4 2',
'edu_prof_qual1'=>'Edu prof qual1',
'edu_prof_qual2'=>'Edu prof qual2',
'edu_prof_qual3'=>'Edu prof qual3',
'edu_prof_qual4'=>'Edu prof qual4',
'edu_prof_qual5'=>'Edu prof qual5',
'edu_prof_qual6'=>'Edu prof qual6',
'emp_rec1'=>'Emp rec1',
'emp_rec2'=>'Emp rec2',
'emp_rec3'=>'Emp rec3',
'emp_rec4'=>'Emp rec4',
'emp_rec5'=>'Emp rec5',
 */
'job_description'=>'Maximum length is <b>300</b> characters',
/*
'affiliation'=>'Affiliation',
'designation'=>'Designation',
*/
'email_1'=>'This E-mail address will use as your username  to login to the system',
/*
'telephone_1'=>'Telephone 1',
'mobile_1'=>'Mobile 1',
 */
'address1_1'=>'Your street address eg: 24/1, First cross street'
/*
'address2_1'=>'Address2 1',
'address3_1'=>'Address3 1',
'email_2'=>'Email 2',
'telephone_2'=>'Telephone 2',
'mobile_2'=>'Mobile 2',
'address1_2'=>'Address1 2',
'address2_2'=>'Address2 2',
'address3_2'=>'Address3 2',
'city'=>'City',
'state'=>'State',
'zip'=>'Zip',
'country'=>'Country',
'referee_name1'=>'Referee name1',
'referee_designation1'=>'Referee designation1',
'referee_work_place1'=>'Referee work place1',
'referee_address1'=>'Referee address1',
'referee_phone1'=>'Referee phone1',
'referee_email1'=>'Referee email1',
'referee_name2'=>'Referee name2',
'referee_designation2'=>'Referee designation2',
'referee_work_place2'=>'Referee work place2',
'referee_address2'=>'Referee address2',
'referee_phone2'=>'Referee phone2',
'referee_email2'=>'Referee email2',
'password'=>'Password',
'functions'=>'Functions',
'last_login'=>'Last login',
'status'=>'Status',
'updated_time'=>'Updated time'
 */
);
 ?>
