<!--Auto generated by form_gen.php-->
<?php
$help_array=array(
'course_id'=>'Course id',
'short_name'=>'Short name',
'long_name'=>'Long name',
'course_fee'=>'Course fee',
'seating_limit'=>'Seating limit',
'venue'=>'Venue',
'time'=>'Time',
'lecturer'=>'Lecturer',
'administrator'=>'Administrator',
'contact_number'=>'Contact number',
'desc'=>'Desc');
 ?>
