<?php
/*Auto generated by form_gen.php*/
$fields=array(
	
"hall_id"=>array(
		"length"=>"77",
		"dojoType"=>"dijit.form.NumberTextBox",
		"required"=>"true",
		"label"=>"Hall id",
		"value"=>""),	
"center"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.SimpleTextarea",
		"required"=>"false",
		"label"=>"Center",
		"value"=>""),	
"hall"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.SimpleTextarea",
		"required"=>"false",
		"label"=>"Hall",
		"value"=>""),	
"no_of_rooms"=>array(
		"length"=>"77",
		"dojoType"=>"dijit.form.NumberTextBox",
		"required"=>"false",
		"label"=>"No of rooms",
		"value"=>""),	
"sutdents_per_room"=>array(
		"length"=>"77",
		"dojoType"=>"dijit.form.NumberTextBox",
		"required"=>"false",
		"label"=>"Sutdents per room",
		"value"=>""),	
"center_id"=>array(
		"length"=>"77",
		"dojoType"=>"dijit.form.NumberTextBox",
		"required"=>"true",
		"label"=>"Center id",
		"value"=>""),	
"center_address"=>array(
		"length"=>"100",
		"dojoType"=>"dijit.form.SimpleTextarea",
		"required"=>"false",
		"label"=>"Center address",
		"value"=>""),	
"sutdents_allocated"=>array(
		"length"=>"77",
		"dojoType"=>"dijit.form.NumberTextBox",
		"required"=>"false",
		"disabled"=>"true",
		"label"=>"Sutdents allocated",
		"value"=>""),
"hid"=>array(
		"length"=>"77",
		"dojoType"=>"dijit.form.NumberTextBox",
		"required"=>"true",
		"type"=>"hidden",
		"label"=>"Short code",
		"value"=>"")	
);

?>
