<!--Auto generated by form_gen.php-->
<?php
$help_array=array(
'hall_id'=>'Hall id',
'center'=>'Center',
'hall'=>'Hall',
'no_of_rooms'=>'No of rooms',
'sutdents_per_room'=>'Sutdents per room',
'center_id'=>'Center id',
'center_address'=>'Center address',
'sutdents_allocated'=>'Sutdents allocated',
'hid'=>'Hid');
 ?>
