<!--Auto generated by form_gen.php-->
<?php
$help_array=array(
'course_code'=>'Course code',
'description'=>'Description',
'coordinator_name'=>'Coordinator name',
'coordinator_email'=>'Coordinator email',
'coordinator_phone'=>'Coordinator phone',
'disabled'=>'Disabled',
'deleted'=>'Deleted',
'note'=>'Note');
 ?>