<!--Auto generated by form_gen.php-->
<?php
$help_array=array(
'batch_id'=>'Batch id',
'course_code'=>'Course code',
'description'=>'Description',
'start_date'=>'Start date',
'end_date'=>'End date',
'start_time'=>'Start time',
'end_time'=>'End time',
'venue'=>'Venue',
'disabled'=>'Disabled',
'deleted'=>'Deleted',
'note'=>'Note');
 ?>