<!--Auto generated by form_gen.php-->
<?php
$help_array=array(
'course_code'=>'Maximum length of course_code is 8 digits which can include only UPPER case characters and numbers',
'description'=>'Description',
'coordinator_name'=>'Coordinator name',
'coordinator_email'=>'Coordinator email',
'coordinator_phone'=>'Coordinator phone',
'disabled'=>'Disabled',
'deleted'=>'Deleted',
'note'=>'Note');
 ?>
