<!--Auto generated by form_gen.php-->
<?php
$help_array=array(
'id'=>'Id',
'batch_id'=>'Batch id',
'registration_no'=>'Registration no',
'payment_status'=>'Payment status',
'payment_method'=>'Payment method',
'transaction_id'=>'Transaction id',
'reserved'=>'Reserved',
'updated_time'=>'Updated time');
 ?>