<?php
/*Auto generated by form_gen.php*/
$fields=array(
	
"course_code"=>array(
		"length"=>"140",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Course code",
		"value"=>""),	
"description"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Description",
		"value"=>""),	
"coordinator_name"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Coordinator name",
		"value"=>""),	
"coordinator_email"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Coordinator email",
		"value"=>""),	
"coordinator_phone"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Coordinator phone",
		"value"=>""),	
"disabled"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.NumberTextBox",
		"required"=>"false",
		"label"=>"Disabled",
		"value"=>""),	
"deleted"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.NumberTextBox",
		"required"=>"false",
		"label"=>"Deleted",
		"value"=>""),	
"note"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.SimpleTextarea",
		"required"=>"false",
		"label"=>"Note",
		"value"=>"")	
);
?>
