<?php
$status_inner="";
//foreach(array("PROF","DR","MR","MS","MRS","REV") as $value){
foreach(array("CONFIRMED","PENDING","RESERVED","CANCELLED","TRANSFERRED") as $value){
	$status_inner.="<option value='$value'>$value</option>";
}

/*Auto generated by form_gen.php*/
$fields=array(
	
"reg_id"=>array(
		"length"=>"63",
		"dojoType"=>"dijit.form.NumberTextBox",
		"type"=>"hidden",
		"required"=>"true",
		"label"=>"Reg id",
		"value"=>""),	
"session_id"=>array(
		"length"=>"63",
		"dojoType"=>"dijit.form.NumberTextBox",
		"required"=>"true",
		"label"=>"Session id",
		"value"=>""),	
"student_id"=>array(
		"length"=>"63",
		"dojoType"=>"dijit.form.NumberTextBox",
		"required"=>"true",
		"label"=>"Student id",
		"value"=>""),	
"status"=>array(
		"length"=>"140",
		"dojoType"=>"dijit.form.ComboBox",
		"inner"=>$status_inner,
		"required"=>"false",
		"label"=>"Status",
		"value"=>""),	
"payment_method"=>array(
		"length"=>"140",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"label"=>"Payment method",
		"value"=>""),	
"payment_id"=>array(
		"length"=>"140",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"label"=>"Payment id",
		"value"=>""),
"certificate_id"=>array(
		"length"=>"140",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"label"=>"Certificate id",
		"value"=>"")		
);
?>
