<?php
/*Auto generated by form_gen.php*/
$payment_status_inner="";
foreach(array("PENDING","ACCEPTED","REJECTED") as $value){
	$payment_status_inner.="<option value='$value'>$value</option>";
}

$payment_method_inner="";
foreach(array("ONLINE","OFFLINE") as $value){
	$payment_method_inner.="<option value='$value'>$value</option>";
}

$fields=array(
	
"enroll_id"=>array(
		"length"=>"77",
		"dojoType"=>"dijit.form.NumberTextBox",
		"type"=>"hidden",
		"required"=>"true",
		"label"=>"Enrollment Id",
		"label_pos"=>"top",
		"value"=>""),	
"batch_id"=>array(
		"length"=>"140",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Batch id",
		"label_pos"=>"top",
		"value"=>""),	
"registration_no"=>array(
		"length"=>"56",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Registration no",
		"label_pos"=>"top",
		"value"=>""),	
"payment_status"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.Select",
		"required"=>"false",
		"inner"=>$payment_status_inner,
		"label"=>"Payment status",
		"label_pos"=>"top",
		"value"=>""),	
"payment_method"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.Select",
		"required"=>"false",
		"inner"=>$payment_method_inner,
		"label"=>"Payment method",
		"label_pos"=>"top",
		"value"=>""),	
"transaction_id"=>array(
		"length"=>"140",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"label"=>"Transaction id",
		"label_pos"=>"top",
		"value"=>""),	
"reserved"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.CheckBox",
		"required"=>"false",
		"label"=>"Reserved",
		"label_pos"=>"right",
		"value"=>""),	
"updated_time"=>array(
		"length"=>"100",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Updated time",
		"label_pos"=>"top",
		"value"=>"")	
);
?>
