<!--Auto generated by form_gen.php-->
<?php
$help_array=array(
'session_id'=>'Session id',
'course_id'=>'Course id',
'session_name'=>'Session name',
'start_date'=>'Start date',
'end_date'=>'End date');
 ?>
