<?php
$title_inner="";
//foreach(array("PROF","DR","MR","MS","MRS","REV") as $value){
foreach(array("REV","DR","MR","MS","MRS","MISS") as $value){
	$title_inner.="<option value='$value'>$value</option>";
}


/*Auto generated by form_gen.php*/
$fields=array(
	
"student_id"=>array(
		"length"=>"63",
		"dojoType"=>"dijit.form.NumberTextBox",
		"type"=>"hidden",
		"required"=>"false",
		"label"=>"Student id",
		"value"=>""),	
"email"=>array(
		"length"=>"200",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"regExp"=>"\b[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}\b",
		"invalidMessage"=>"Please enter a valid email address",
		"required"=>"true",
		"label"=>"Email",
		"value"=>""),	
"NIC"=>array(
		"length"=>"140",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"NIC",
		"value"=>""),	
"title"=>array(
		"length"=>"40",
		"dojoType"=>"dijit.form.ComboBox",
		"required"=>"true",
		"inner"=>$title_inner,
		"label"=>"Title",
		"value"=>""),	
"first_name"=>array(
		"length"=>"240",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"First name",
		"value"=>""),	
"middle_names"=>array(
		"length"=>"240",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"label"=>"Middle names",
		"value"=>""),	
"last_name"=>array(
		"length"=>"240",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Last name",
		"value"=>""),	
"address_line_1"=>array(
		"length"=>"380",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Address line 1",
		"value"=>""),	
"address_line_2"=>array(
		"length"=>"380",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Address line 2",
		"value"=>""),	
"address_line_3"=>array(
		"length"=>"380",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"label"=>"Address line 3",
		"value"=>""),	
"city"=>array(
		"length"=>"280",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"City",
		"value"=>""),	
"province"=>array(
		"length"=>"280",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"label"=>"Province",
		"value"=>""),	
"phone_num_1"=>array(
		"length"=>"105",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"regExp"=>"^0[0-9]{9}$",
		"invalidMessage"=>"Please enter a valid phone number",		
		"label"=>"Personal phone",
		"value"=>""),	
"phone_num_2"=>array(
		"length"=>"105",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"regExp"=>"^0[0-9]{9}$",
		"invalidMessage"=>"Please enter a valid phone number",		
		"label"=>"Office phone",
		"value"=>"")	
);
?>
