<!--Auto generated by form_gen.php-->
<?php
$help_array=array(
/*'student_id'=>'Student id',
'email'=>'Email',
'NIC'=>'Nic',
'title'=>'Title',
'first_name'=>'First name',
'last_name'=>'Last name',
'address_line_1'=>'Address line 1',
'address_line_2'=>'Address line 2',
'address_line_3'=>'Address line 3',
'town'=>'Town',
'province'=>'Province',
'phone_num_1'=>'Phone num 1',
'phone_num_2'=>'Phone num'*/);

if(isset($_REQUEST['help']) && $_REQUEST['help'] == true){
?>

<?php
}
 ?>
