<!--Auto generated by form_gen.php-->
<?php
$help_array=array(
'batch_id'=>'Batch id',
'admission_year'=>'Admission year',
'code'=>'Code',
'date_of_addmission'=>'Date of addmission',
'deleted'=>'Deleted',
'note'=>'Note');
 ?>