<?php
/*Auto generated by form_gen.php*/
$fields=array(
	
"batch_id"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Batch id",
		"value"=>""),	
"admission_year"=>array(
		"length"=>"105",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"label"=>"Admission year",
		"value"=>""),	
"code"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"label"=>"Code",
		"value"=>""),	
"date_of_addmission"=>array(
		"length"=>"100",
		"dojoType"=>"dijit.form.DateTextBox",
		"required"=>"false",
		"label"=>"Date of addmission",
		"value"=>""),	
"deleted"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.NumberTextBox",
		"required"=>"false",
		"label"=>"Deleted",
		"value"=>""),	
"note"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.SimpleTextarea",
		"required"=>"false",
		"label"=>"Note",
		"value"=>"")	
);
?>
