<!--Auto generated by form_gen.php-->
<style type='text/css'>.helptt{max-width:400px;border-top:1px solid silver;text-align:justify;}</style>
<div dojoType='dijit.Tooltip' connectId='index_no' >
   <b>HELP:</b>
   <div class='helptt'>
      Index no
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='full_name' >
   <b>HELP:</b>
   <div class='helptt'>
      Full name
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='initials' >
   <b>HELP:</b>
   <div class='helptt'>
      Initials
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='last_name' >
   <b>HELP:</b>
   <div class='helptt'>
      Last name
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='perm_address' >
   <b>HELP:</b>
   <div class='helptt'>
      Perm address
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='curr_address' >
   <b>HELP:</b>
   <div class='helptt'>
      Curr address
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='phone' >
   <b>HELP:</b>
   <div class='helptt'>
      Phone
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='sex' >
   <b>HELP:</b>
   <div class='helptt'>
      Sex
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='title' >
   <b>HELP:</b>
   <div class='helptt'>
      Title
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='NID' >
   <b>HELP:</b>
   <div class='helptt'>
      Nid
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='current_year' >
   <b>HELP:</b>
   <div class='helptt'>
      Current year
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='degree_GPA' >
   <b>HELP:</b>
   <div class='helptt'>
      Degree gpa
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='class_GPA' >
   <b>HELP:</b>
   <div class='helptt'>
      Class gpa
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='date_of_regist' >
   <b>HELP:</b>
   <div class='helptt'>
      Date of regist
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='date_of_graduation' >
   <b>HELP:</b>
   <div class='helptt'>
      Date of graduation
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='date_of_birth' >
   <b>HELP:</b>
   <div class='helptt'>
      Date of birth
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='province' >
   <b>HELP:</b>
   <div class='helptt'>
      Province
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='district' >
   <b>HELP:</b>
   <div class='helptt'>
      District
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='nationality' >
   <b>HELP:</b>
   <div class='helptt'>
      Nationality
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='religion' >
   <b>HELP:</b>
   <div class='helptt'>
      Religion
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='ugc_z_score' >
   <b>HELP:</b>
   <div class='helptt'>
      Ugc z score
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='z_score' >
   <b>HELP:</b>
   <div class='helptt'>
      Z score
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='AL_index_no' >
   <b>HELP:</b>
   <div class='helptt'>
      Al index no
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='AL_subject' >
   <b>HELP:</b>
   <div class='helptt'>
      Al subject
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='AL_result' >
   <b>HELP:</b>
   <div class='helptt'>
      Al result
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='AL_general_english' >
   <b>HELP:</b>
   <div class='helptt'>
      Al general english
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='AL_general_knowledge' >
   <b>HELP:</b>
   <div class='helptt'>
      Al general knowledge
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='AL_district' >
   <b>HELP:</b>
   <div class='helptt'>
      Al district
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='AL_district_no' >
   <b>HELP:</b>
   <div class='helptt'>
      Al district no
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='photo' >
   <b>HELP:</b>
   <div class='helptt'>
      Photo
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='amount' >
   <b>HELP:</b>
   <div class='helptt'>
      Amount
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='date_of_paid' >
   <b>HELP:</b>
   <div class='helptt'>
      Date of paid
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='paid_branch' >
   <b>HELP:</b>
   <div class='helptt'>
      Paid branch
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='registered' >
   <b>HELP:</b>
   <div class='helptt'>
      Registered
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='deleted' >
   <b>HELP:</b>
   <div class='helptt'>
      Deleted
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='status' >
   <b>HELP:</b>
   <div class='helptt'>
      Status
   </div>
</div>
<div dojoType='dijit.Tooltip' connectId='note' >
   <b>HELP:</b>
   <div class='helptt'>
      Note
   </div>
</div>
