<!--Auto generated by form_gen.php-->
<?php
$help_array=array(
/*
'index_no'=>'Index no',
'full_name'=>'Full name',
'initials'=>'Initials',
'last_name'=>'Last name',
'permanent_address'=>'Permanent address',
'current_address'=>'Current address',
'phone'=>'Phone',
'sex'=>'Sex',
'title'=>'Title',
*/
'NID'=>'NIC number of the student',
/*
'current_year'=>'Current year',
'degree_GPA'=>'Degree gpa',
'class_GPA'=>'Class gpa',
'date_of_regist'=>'Date of regist',
'date_of_graduation'=>'Date of graduation',
'date_of_birth'=>'Date of birth',
'province'=>'Province',
'district'=>'District',
'nationality'=>'Nationality',
'religion'=>'Religion',
'ugc_z_score'=>'Ugc z score',
'z_score'=>'Z score',
'AL_index_no'=>'Al index no',
'AL_subject'=>'Al subject',
'AL_result'=>'Al result',
'AL_general_english'=>'Al general english',
'AL_general_knowledge'=>'Al general knowledge',
'AL_district'=>'Al district',
'AL_district_no'=>'Al district no',
'photo'=>'Photo',
'amount'=>'Amount',
'date_of_paid'=>'Date of paid',
'paid_branch'=>'Paid branch',
'registered'=>'Registered',
'deleted'=>'Deleted',
'status'=>'Status',
'note'=>'Note',
'registration_no'=>'Registration no',
'batch'=>'Batch'
*/

);
 ?>
