<!--Auto generated by form_gen.php-->
<?php
$help_array=array(
'reg_id'=>'Reg id',
'session_id'=>'Session id',
'student_id'=>'Student id',
'status'=>'Status',
'payment_method'=>'Payment method',
'payment_id'=>'Payment id');
 ?>
