<?php
$display_inner="
<option value='YES'>YES</option>
<option value='NO'>NO</option>
";


$tableq = $GLOBALS['MOD_P_TABLES']["course"];
$query = "SELECT * FROM ".$tableq;
$res = exec_query($query,Q_RET_MYSQL_RES);
$course_inner="";
while($row = mysql_fetch_array($res))
  {
  $value = $row['course_id'];
   $course_inner .= "<option value=".$row['course_id'] .">".$row['course_id']."</option>";
  }


/*Auto generated by form_gen.php*/
$fields=array(
	
"session_id"=>array(
		"length"=>"63",
		"dojoType"=>"dijit.form.NumberTextBox",
		"type"=>"hidden",
		"required"=>"false",
		"label"=>"Session id",
		"value"=>""),	
"course_id"=>array(
		"length"=>"63",
		"dojoType"=>"dijit.form.ComboBox",
		"required"=>"true",
		"inner"=>$course_inner,
		"label"=>"Course id",
		"value"=>""),	
"session_name"=>array(
		"length"=>"210",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"label"=>"Session name",
		"value"=>""),	
"start_date"=>array(
		"length"=>"100",
		"dojoType"=>"dijit.form.DateTextBox",
		"required"=>"false",
		"label"=>"Start date",
		"value"=>""),	
"end_date"=>array(
		"length"=>"100",
		"dojoType"=>"dijit.form.DateTextBox",
		"required"=>"false",
		"label"=>"End date",
		"value"=>""),
"display"=>array(
		"length"=>"200",
		"dojoType"=>"dijit.form.ComboBox",
		"inner"=>$display_inner,		
		"required"=>"true",
		"label"=>"Available",
		"value"=>"YES")		
);
?>
