<?php
/*Auto generated by form_gen.php*/
$fields=array(
	
"bank_id"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.NumberTextBox",
		"type"=>"hidden",
		"required"=>"true",
		"label"=>"Bank id",
		"value"=>""),	
"bank_name"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.SimpleTextarea",
		"required"=>"true",
		"label"=>"Bank name",
		"value"=>""),	
"root_dir"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.SimpleTextarea",
		"required"=>"true",
		"label"=>"Root dir",
		"value"=>""),	
"gateway_url"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.SimpleTextarea",
		"required"=>"true",
		"label"=>"Gateway url",
		"value"=>""),	
"callback_url"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.SimpleTextarea",
		"required"=>"true",
		"label"=>"Callback url",
		"value"=>""),	
"igpkey_dir"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.SimpleTextarea",
		"required"=>"true",
		"label"=>"Igpkey dir",
		"value"=>""),	
"note"=>array(
		"length"=>"100",
		"dojoType"=>"dijit.form.SimpleTextarea",
		"required"=>"false",
		"label"=>"Note",
		"value"=>"")	
);
?>
