<!--Auto generated by form_gen.php-->
<?php
$help_array=array(
'pay_for_id'=>'Pay for id',
'program_id'=>'Program id',
'short_name'=>'Short name',
'description'=>'Description',
'amount'=>'Amount',
'tax'=>'Tax',
'registration'=>'Registration',
'pay_for_code'=>'Code',
'coordinator'=>'Coordinator',
'deleted'=>'Deleted',
'note'=>'Note');
 ?>
