<?php
/*Auto generated by form_gen.php*/
$paper_id_select="";
$res=exec_query("SELECT course_id FROM ".$GLOBALS['P_TABLES']['course'],1);
while($row=mysql_fetch_assoc($res)){
   $paper_id_select.="<option value='".$row['course_id']."'>".$row['course_id']."</option>";
}
$fields=array(
   
"paper_id"=>array(
      "length"=>"77",
      "dojoType"=>"dijit.form.ComboBox",
      "required"=>"true",
      "label"=>"Paper id",
      "value"=>$paper_id_select),   
"index_regexp"=>array(
      "length"=>"56",
      "dojoType"=>"dijit.form.ValidationTextBox",
      "required"=>"true",
      "label"=>"Index regexp",
      "value"=>""),   
"push"=>array(
      "length"=>"100",
      "dojoType"=>"dijit.form.ValidationTextBox",
      "required"=>"false",
      "label"=>"Push",
      "value"=>""),   
"deleted"=>array(
      "length"=>"70",
      "dojoType"=>"dijit.form.NumberTextBox",
      "required"=>"false",
      "label"=>"Deleted",
      "value"=>""),   
"note"=>array(
      "length"=>"350",
      "dojoType"=>"dijit.form.SimpleTextarea",
      "required"=>"false",
      "label"=>"Note",
      "value"=>"")   
);
?>
