<!--Auto generated by form_gen.php-->
<?php
$help_array=array(
'exam_id'=>'Exam id',
'exam_hid'=>'Exam hid',
'exam_old_id'=>'Exam old id',
'semester'=>'Semester',
'student_year'=>'Student year',
'academic_year'=>'Academic year',
'exam_date'=>'Exam date',
'exam_time'=>'Exam time',
'venue'=>'Venue',
'deleted'=>'Deleted',
'note'=>'Note');
 ?>
