<?php
/*
$paper_must_custom='
   <div>Paper must do<span style="color:red">*</span></div>
   <input id="paper_must_ok" jsId="paper_must_ok" name="paper_must_radio" value="1" dojoType="dijit.form.RadioButton" type="radio"
   onClick="
      document.getElementById(\'paper_must\').value=this.value;
   "; 
   />
   YES
   <input id="paper_must_no" jsId="paper_must_no" name="paper_must_radio" value="0" dojoType="dijit.form.RadioButton" type="radio"
     onClick="
      document.getElementById(\'paper_must\').value=this.value;
   ";
   />
   NO
';
 */


/*Auto generated by form_gen.php*/
$fields=array(
   
"exam_hid"=>array(
      "length"=>"160",
      "dojoType"=>"dijit.form.ComboBox",
      "required"=>"true",
      "onChange"=>'set_param("exam_hid",this.value)',
      "searchAttr"=>"exam_hid",
      "store"=>"exam_hid_store",
      "pageSize"=>"10",
      "label"=>"Exam id HR [date:year:semester]"),   
"course_id"=>array(
      "length"=>"100",
      "dojoType"=>"dijit.form.ComboBox",
      "required"=>"true",
      "onChange"=>'set_param("course_id",this.value);fill_form(this.value)',
      "label"=>"Course id",
      "searchAttr"=>"course_id",
      "pageSize"=>"10",
      "store"=>"course_id_store"
      ),   
"paper"=>array(
      "length"=>"70",
      "dojoType"=>"dijit.form.NumberTextBox",
      "required"=>"false",
      "onChange"=>'document.getElementById("assignment").value=(100-this.value)',
      "label"=>"Paper weight",
      "value"=>""),   
"assignment"=>array(
      "length"=>"70",
      "dojoType"=>"dijit.form.NumberTextBox",
      "required"=>"false",
      "type"=>"hidden",
      "onChange"=>'document.getElementById("paper").value=(100-this.value)',
      "label"=>"Assignment weight",
      "value"=>""),   
"paper_must"=>array(
      "dojoType"=>"dijit.form.CheckBox",
      "required"=>"false",
      "label_pos"=>"right",
      "label"=>"Paper must do",
      "value"=>"1"),   
/*
"paper_must_cust"=>array(
      "custom"=>"true",
      "inner"=>$paper_must_custom,
      "label"=>"",
      ),
"paper_must"=>array(
      "dojoType"=>"dijit.form.NumberTextBox",
      "required"=>"false",
      "onChange"=>$pape_must_onChange,
      "label"=>"",
      "value"=>""),   
 */
"assignment_must"=>array(
      "dojoType"=>"dijit.form.CheckBox",
      "required"=>"false",
      "label_pos"=>"right",
      "label"=>"Assignment must do",
      "value"=>"1"),   
"note"=>array(
      "length"=>"350",
      "dojoType"=>"dijit.form.SimpleTextarea",
      "required"=>"false",
      "label"=>"Note",
      "value"=>"")   
);
?>
