<!--Auto generated by form_gen.php-->
<?php
$help_array=array(
//'exam_id'=>'Exam id',
//'course_id'=>'Course id',
'paper_rubric'=>'Paper rubric',
'assignment_rubric'=>'Assignment rubric',
'deleted'=>'Deleted',
'note'=>'Note');
 ?>
