<!--Auto generated by form_gen.php-->
<?php
$help_array=array(
//'index_no'=>'Index no',
//'year'=>'Year',
//'name'=>'Name',
'name_in_english'=>'Please write the name carefully using block capital letters. This name will included in your degree certificate',
'name_in_sinhala'=>'Please write the name carefully using a unicode font. This name will included in your degree certificate',
'name_in_tamil'=>'Please write the name carefully using a unicode font.  This name will included in your degree certificate',
//'category'=>'Category',
'awarded_in'=>'If you are not going to present for the convocation please select IN_ABSENTIA'
//'guest_tickets'=>'Guest tickets'
);
 ?>
