<?php
d_r('dojox.form.PasswordValidator');
d_r('dijit.form.DropDownButton');
d_r('dijit.form.Button');
d_r('dijit.form.ValidationTextBox');
d_r('dijit.TooltipDialog');

$awarded_in_inner="
<option>IN_PERSON</option>
<option>IN_ABSENTIA</option>
";

$pay_offline_status_inner="
<option></option>
<option>PENDING</option>
<option>ACCEPTED</option>
";

$category_inner="
<option>MSC</option>
<option>MPHIL</option>
<option>DIP</option>
";

$guest_tickets_inner="
<option>0</option>
<option>1</option>
<option>2</option>
";

$email_custom='
<div dojoType="dijit.form.DropDownButton">
	<span>
       Click to enter email 
   </span>
   <div dojoType="dijit.TooltipDialog">
		<label for="email_new">Email</label><br>
		<input type="text" 
			jsId		="email_new"  
			dojoType	="dijit.form.ValidationTextBox" 
			required	="true" 
			regExp	="\b[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}\b" 
			prompMessage	="Enter email address"
			invalidMessage	="Please enter a valid email address" 
			trim=true
		><br>
      <label for="email_verify" >Validate</label><br>
		<input type="text" 
			jsId		="email_verify"  
			dojoType	="dijit.form.ValidationTextBox" 
			required	="true" 
			regExp	="\b[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}\b" 
			prompMessage	="Validate email address"
			invalidMessage="Please enter a valid email address" 
			trim=true
		>

		<div id="msg"></div>
      <button dojoType="dijit.form.Button" type="submit">
         OK
  			<script type="dojo/method" event="onClick" args="evt">
				var em_new=email_new.value;
				var em_ver=email_verify.value;

				if(em_new == em_ver){
					email.attr("value",em_ver);
					return true;
				}else{
					document.getElementById("msg").innerHTML="<font color=\"red\">Email validation failed</font>";
				}
				return false;
			</script>
      </button>
   </div>
</div>
<input  name="email" id="email" jsId="email" dojoType="dijit.form.ValidationTextBox" readOnly=true value="%s" style="border:0px;" ></input>
';


/*Auto generated by form_gen.php*/

$fields=array(
	
"index_no"=>array(
		"length"=>"105",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"section"=>"Pleae fill the form and press next button",
		"type"=>"hidden",
		"label"=>"Index no",
		"value"=>""),	
"reg_no"=>array(
		"length"=>"105",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"type"=>"hidden",
		"label"=>"Registratio number",
		"value"=>""),	
"nic"=>array(
		"length"=>"150",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		//"regExp"=>"\b[0-9]{9}[v]?\b",
		"regExp"=>"\b[0-9]{9}[v]{1}\b",
		"prompMessage"	=>"Validate NIC Number",
		"invalidMessage"=>"Please enter a valid NIC Number",
		"label"=>"NIC Number",
		"value"=>""),	
/*
"name"=>array(
		"length"=>"400",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"disabled"=>"true",
		"label"=>"Name with initials",
		"value"=>""),	
*/
"name_in_english"=>array(
		"length"=>"450",
		"section"=>"Enter your full name in all three languages. Your degree certificate will be printed using the spelling supplied by you. If you do not fill the name in Sinhala and Tamill the system generated name will apear in your certificate",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Full Name in English",
		"value"=>""),	
"name_in_sinhala"=>array(
		"length"=>"450",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"label"=>"Full Name in Sinhala",
		"value"=>""),	
"name_in_tamil"=>array(
		"length"=>"450",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"label"=>"Full Name in Tamil",
		"value"=>""),	
"awarded_in"=>array(
		"length"=>"110",
		"dojoType"=>"dijit.form.ComboBox",
		"required"=>"true",
		"section"=>"State if you intend to attend the Convocation and if so the number of guest tickets required",
		"inner"=>$awarded_in_inner,
		"label"=>"Awarded in person or in absentia",
		"value"=>""),	
"guest_tickets"=>array(
		"length"=>"40",
		"dojoType"=>"dijit.form.ComboBox",
		"required"=>"false",
		"inner"=>$guest_tickets_inner,
		"label"=>"Number of guest tickets required (if awarded in person)",
		"value"=>""),	
/*
"client_ip"=>array(
		"length"=>"40",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"label"=>"",
		"type"=>"hidden",
		"value"=>$_SERVER['REMOTE_ADDR']),
*/
"current_level"=>array(
		"length"=>"40",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"label"=>"",
		"type"=>"hidden",
		"value"=>"1")

);


$fields_admin=array(
"index_no"=>array(
		"length"=>"140",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"disabled"=>"true",
		"label"=>"Index no",
		"value"=>""),	
"reg_no"=>array(
		"length"=>"140",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"disabled"=>"true",
		"label"=>"Reg no",
		"value"=>""),	
"name"=>array(
		"length"=>"100",
		"dojoType"=>"dijit.form.SimpleTextarea",
		"required"=>"true",
		"label"=>"Name",
		"value"=>""),	
"nic"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Nic",
		"value"=>""),	
"email"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"disabled"=>"true",
		"label"=>"Email",
		"value"=>""),	
"name_in_english"=>array(
		"length"=>"300",
		"dojoType"=>"dijit.form.SimpleTextarea",
		"required"=>"true",
		"label"=>"Name in english",
		"value"=>""),	
"name_in_sinhala"=>array(
		"length"=>"300",
		"dojoType"=>"dijit.form.SimpleTextarea",
		"required"=>"true",
		"label"=>"Name in sinhala",
		"value"=>""),	
"name_in_tamil"=>array(
		"length"=>"300",
		"dojoType"=>"dijit.form.SimpleTextarea",
		"required"=>"true",
		"label"=>"Name in tamil",
		"value"=>""),	
"category"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.ComboBox",
		"required"=>"true",
		"label"=>"Category",
		"inner"=>$category_inner,
		"value"=>""),	
"awarded_in"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.ComboBox",
		"required"=>"true",
		"label"=>"Awarded in",
		"inner"=>$awarded_in_inner,
		"value"=>""),	
"guest_tickets"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.ComboBox",
		"required"=>"true",
		"inner"=>$guest_tickets_inner,
		"label"=>"Guest tickets",
		"value"=>""),	
"pay_online"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.NumberTextBox",
		"required"=>"false",
		"disabled"=>"true",
		"label"=>"Pay online",
		"value"=>""),	
"pay_online_status"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"disabled"=>"true",
		"required"=>"true",
		"label"=>"Pay online status",
		"value"=>""),	
"pay_offline_status"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.ComboBox",
		"required"=>"true",
		"label"=>"Pay offline status",
		"inner"=>$pay_offline_status_inner,
		"value"=>""),	
"transaction_id"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"disabled"=>"true",
		"label"=>"Transaction id",
		"value"=>""),	
"updated_time"=>array(
		"length"=>"100",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"disabled"=>"true",
		"label"=>"Updated time",
		"value"=>""),	
"client_ip"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.SimpleTextarea",
		"disabled"=>"true",
		"required"=>"false",
		"label"=>"Client ip",
		"value"=>"")	
);

if($GLOBALS['LAYOUT'] != 'pub'){
	$fields=$fields_admin;
}

?>
