<?php
$semester_inner="
<option value='1'>1</option>
<option value='2'>2</option>
<option value='3'>3</option>
";

$student_year_inner="
<option value='1'>1</option>
<option value='2'>2</option>
<option value='3'>3</option>
<option value='4'>4</option>
";



/*Auto generated by form_gen.php*/
$fields=array(
	
"course_id"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Course id",
		"value"=>""),	
"student_year"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.ComboBox",
		"required"=>"false",
		"inner"=>$student_year_inner,
		"label"=>"Student year",
		"value"=>""),	
"semester"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.ComboBox",
		"required"=>"false",
		"inner"=>$semester_inner,
		"label"=>"Semester",
		"value"=>""),	
"course_name"=>array(
		"length"=>"420",
		"dojoType"=>"dijit.form.SimpleTextarea",
		"required"=>"false",
		"label"=>"Course name",
		"value"=>""),	
"prerequisite"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"label"=>"Prerequisite",
		"value"=>""),	
"lecture_credits"=>array(
		"length"=>"42",
		"dojoType"=>"dijit.form.NumberTextBox",
		"required"=>"false",
		"label"=>"Lecture credits",
		"value"=>""),	
"practical_credits"=>array(
		"length"=>"42",
		"dojoType"=>"dijit.form.NumberTextBox",
		"required"=>"false",
		"label"=>"Practical credits",
		"value"=>""),	
"maximum_students"=>array(
		"length"=>"42",
		"dojoType"=>"dijit.form.NumberTextBox",
		"required"=>"false",
		"label"=>"Maximus students",
		"value"=>""),	
"compulsory"=>array(
		"dojoType"=>"dijit.form.CheckBox",
		"required"=>"false",
		"label_pos"=>"right",
		"label"=>"Compulsory",
		"value"=>"1"),	
"alt_course_id"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"label"=>"Alt course id",
		"value"=>""),	
"offered_by"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"label"=>"Offered by",
		"value"=>""),	
"non_gpa"=>array(
		"dojoType"=>"dijit.form.CheckBox",
		"required"=>"true",
		"label"=>"Non gpa",
		"label_pos"=>"right",
		"value"=>"1"),	

"non_credit"=>array(
		"dojoType"=>"dijit.form.CheckBox",
		"required"=>"true",
		"label_pos"=>"right",
		"label"=>"Non credit",
		"value"=>"1"),	

/*
"deleted"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.NumberTextBox",
		"required"=>"false",
		"label"=>"Deleted",
		"value"=>""),	
 */
"note"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.SimpleTextarea",
		"required"=>"false",
		"label"=>"Note",
		"value"=>"")	
);
?>
