<!--Auto generated by form_gen.php-->
<?php
$help_array=array(
'course_id'=>'Course id',
'student_year'=>'Student year',
'semester'=>'Semester',
'course_name'=>'Course name',
'prerequisite'=>'Prerequisite',
'lecture_credits'=>'Lecture credits',
'practical_credits'=>'Practical credits',
'maximum_students'=>'Maximum students',
'compulsory'=>'Compulsory',
'alt_course_id'=>'Alt course id',
'offered_by'=>'Offered by',
'GPA_con'=>'Gpa con',
'deleted'=>'Deleted',
'note'=>'Note');
 ?>