<?php
d_r("dijit.form.Slider");

$lecture_credits_custom='
<div id="lecture_credits_slider" dojoType="dijit.form.HorizontalSlider" value="%s" minimum="0" maximum="10" discreteValues="11" intermediateChanges="true" showButtons="false" style="width:400px;"
onChange="document.getElementById(\'lecture_credits\').value = this.value;"
>
    <ol dojoType="dijit.form.HorizontalRuleLabels" container="topDecoration" style="height:1.5em;color:gray;">
        <li>0</li>
        <li>1</li>
        <li>2</li>
        <li>3</li>
        <li>4</li>
        <li>5</li>
        <li>6</li>
        <li>7</li>
        <li>8</li>
        <li>9</li>
        <li>10</li>
    </ol>
    <div dojoType="dijit.form.HorizontalRule" container="bottomDecoration" count=11 style="height:5px;">
    </div>
</div>
';

$lecture_credits_custom='
<input dojoType="dijit.form.NumberSpinner"
     value="1000"
     smallDelta="10"
     constraints="{min:9,max:1550,places:0}"
     id="integerspinner2"
     name="someNumber"
     />
';

$semester_inner="
<option value='1'>1</option>
<option value='2'>2</option>
<option value='3'>3</option>
";

$student_year_inner="
<option value='1'>1</option>
<option value='2'>2</option>
<option value='3'>3</option>
<option value='4'>4</option>
";

$offered_by_inner="
<option value='UCSC'>UCSC</option>
<option value='UCFC'>UCFC</option>
<option value='UCFM'>UCFM</option>
<option value='EXTERNAL'>EXTERNAL</option>
";


/*Auto generated by form_gen.php*/
$fields=array(
	
"course_id"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Course id",
		"value"=>""),	
"student_year"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.Select",
		"required"=>"false",
		"inner"=>$student_year_inner,
		"label"=>"Student year",
		"value"=>""),	
"semester"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.Select",
		"required"=>"false",
		"inner"=>$semester_inner,
		"label"=>"Semester",
		"value"=>""),	
"course_name"=>array(
		"length"=>"420",
		"dojoType"=>"dijit.form.SimpleTextarea",
		"required"=>"false",
		"label"=>"Course name",
		"value"=>""),	
"prerequisite"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"label"=>"Prerequisite",
		"value"=>""),	
"lecture_credits"=>array(
		"length"=>"42",
		"dojoType"=>"dijit.form.NumberSpinner",
      "smallDelta"=>"1",
      "constraints"=>"{min:0,max:10,places:0}",
		"required"=>"true",
		"label"=>"Lecture credits",
		"value"=>""),	
/*
"lecture_credits_slider"=>array(
		"label"=>"Lecture credits",
		"custom"=>"true",
      "inner"=>$lecture_credits_custom
      ),	
*/

"practical_credits"=>array(
		"length"=>"42",
		"dojoType"=>"dijit.form.NumberSpinner",
      "smallDelta"=>"1",
      "constraints"=>"{min:0,max:10,places:0}",

		"required"=>"true",
		"label"=>"Practical credits",
		"value"=>""),	
"maximum_students"=>array(
		"length"=>"42",
		"dojoType"=>"dijit.form.NumberSpinner",
      "smallDelta"=>"1",
      "constraints"=>"{min:0,max:100,places:0}",

		"required"=>"false",
		"label"=>"Maximum students",
		"value"=>""),	
/*
"alt_course_id"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"false",
		"label"=>"Alt course id",
		"value"=>""),	
 */
"alt_course_id"=>array(
		"length"=>"100",
		"dojoType"=>"dijit.form.ComboBox",
		"required"=>"false",
		//"onChange"=>'set_param("course_id",this.value);fill_form(this.value)',
		"onChange"=>'set_param("course_id",this.value);fill_form(this.value)',
		"label"=>"Alternate Course id",
		"searchAttr"=>"course_id",
		"pageSize"=>"10",
		"store"=>"course_id_store"
		),	

"offered_by"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.Select",
		"required"=>"false",
      "inner"=>$offered_by_inner,
		"label"=>"Offered by",
		"value"=>""),	
"compulsory"=>array(
		"dojoType"=>"dijit.form.CheckBox",
		"required"=>"false",
		"label_pos"=>"right",
		"label"=>"Compulsory",
		"value"=>"1"),	
"non_grade"=>array(
		"dojoType"=>"dijit.form.CheckBox",
		"required"=>"false",
		"label"=>"Non grade",
		"label_pos"=>"right",
		"value"=>"1"),	
"non_credit"=>array(
		"dojoType"=>"dijit.form.CheckBox",
		"required"=>"false",
		"label_pos"=>"right",
		"label"=>"Non credit",
		"value"=>"1"),	
/*
"deleted"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.NumberTextBox",
		"required"=>"false",
		"label"=>"Deleted",
		"value"=>""),	
 */
"note"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.SimpleTextarea",
		"required"=>"false",
		"label"=>"Note",
		"value"=>"")	
);
?>
