<!--Auto generated by form_gen.php-->
<?php
$help_array=array(
'index_no'=>'Index no',
'course_id'=>'Course id',
'academic_year'=>'Academic year',
'semester'=>'Semester',
'deleted'=>'Deleted',
'note'=>'Note');
 ?>
