<!--Auto generated by form_gen.php-->
<?php
$help_array=array(
'course_id'=>'Course id',
'student_year'=>'Student year',
'semester'=>'Semester',
'course_name'=>'Course name',
'prerequisite'=>'Prerequisite',
'lecture_credits'=>'Lecture credits',
'practical_credits'=>'Practical credits',
'maximum_students'=>'Maximum students',
'alt_course_id'=>'Alt course id',
'offered_by'=>'Offered by',
'compulsory'=>'Compulsory',
'non_grade'=>'No grade will be assigned for these courses instead CM or NC will assign',
'non_mark'=>'Non mark courses have two states CM -&gt; complete and NC -&gt; not complete',
'pass_grade'=>"Pass grade will be 'CM' for <b>non_grade</b> courses and 'C' for others by default",
);
 ?>
