<!--Auto generated by form_gen.php-->
<?php
$help_array=array(
'bank_id'=>'Bank id',
'bank_name'=>'Bank name',
'root_dir'=>'Root dir',
'gateway_url'=>'Gateway url',
'callback_url'=>'Callback url',
'igpkey_dir'=>'Igpkey dir',
'note'=>'Note');
 ?>