<?php
/*Auto generated by form_gen.php*/
$fields=array(
	
"program_id"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.NumberTextBox",
		"type"=>"hidden",
		"required"=>"false",
		"label"=>"Program id",
		"value"=>""),	
"short_name"=>array(
		"length"=>"140",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Short name of the program",
		"value"=>""),	
"description"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Program Title",
		"value"=>""),	
"program_code"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Program code",
		"value"=>""),	
"tp_key"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Third party encryption key",
		"value"=>trim(shell_exec("openssl rand -base64 32"))),
"tp_ip"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Third party host name with proto",
		"value"=>""),	
"tp_callback"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Third party callback URL",
		"value"=>""),	
"coordinator"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Third party coordinator name",
		"value"=>""),	
"tp_mail"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Third party mail",
		"value"=>""),	
"tp_phone"=>array(
		"length"=>"105",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Third party phone",
		"value"=>""),	
/*
"registration"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.ValidationTextBox",
		"required"=>"true",
		"label"=>"Registration",
		"value"=>""),	
"logo"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.SimpleTextarea",
		"required"=>"true",
		"label"=>"Logo",
		"value"=>""),	
*/
/*
"deleted"=>array(
		"length"=>"70",
		"dojoType"=>"dijit.form.NumberTextBox",
		"required"=>"false",
		"label"=>"Deleted",
		"value"=>""),	
*/
"note"=>array(
		"length"=>"350",
		"dojoType"=>"dijit.form.SimpleTextarea",
		"required"=>"false",
		"label"=>"Note",
		"value"=>""),	
);
?>
