<!--Auto generated by form_gen.php-->
<?php
$help_array=array(
'program_id'=>'Program id',
'short_name'=>'Short name',
'full_name'=>'Full name',
'tp_ip'=>'eg: https://ucsc.lk',
'tp_callback'=>'eg: uis/?module=ext_courses&amp;page=callback',
'tp_mail'=>'Tp mail',
'tp_phone'=>'Tp phone',
'description'=>'Description',
'registration'=>'Registration',
'logo'=>'Logo',
'program_code'=>'Code',
'coordinator'=>'Coordinator',
'deleted'=>'Deleted',
'note'=>'Note',
'tp_key'=>'Tp key');
 ?>
